name: .NET

on:
  push:
    branches:
    - "master"


  pull_request:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Inital Submodules 
      run: git submodule update --init --recursive
    - name: Install cake build tool
      run: dotnet tool install Cake.Tool --version 2.0.0
    - name: Test
      run: dotnet cake --target="Test"
